// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0SBPtpRTdtOsWtfosCAKMgpqhTCq3pFM',
    appId: '1:57775464871:web:b9aa01141f57ed48215682',
    messagingSenderId: '57775464871',
    projectId: 'campus-connect-6d87f',
    authDomain: 'campus-connect-6d87f.firebaseapp.com',
    storageBucket: 'campus-connect-6d87f.firebasestorage.app',
    measurementId: 'G-QN1G4DXJRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZg3JXt6t9O8Mic5J4qQ819s36n9e-p5Y',
    appId: '1:57775464871:android:5b68cea9c6da19a5215682',
    messagingSenderId: '57775464871',
    projectId: 'campus-connect-6d87f',
    storageBucket: 'campus-connect-6d87f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZXIfqbrE8ycIqs0eMzhs8NWdWMA_ZA9U',
    appId: '1:57775464871:ios:822ab3a1fa34230a215682',
    messagingSenderId: '57775464871',
    projectId: 'campus-connect-6d87f',
    storageBucket: 'campus-connect-6d87f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZXIfqbrE8ycIqs0eMzhs8NWdWMA_ZA9U',
    appId: '1:57775464871:ios:822ab3a1fa34230a215682',
    messagingSenderId: '57775464871',
    projectId: 'campus-connect-6d87f',
    storageBucket: 'campus-connect-6d87f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0SBPtpRTdtOsWtfosCAKMgpqhTCq3pFM',
    appId: '1:57775464871:web:ffaa34e5ce4dec38215682',
    messagingSenderId: '57775464871',
    projectId: 'campus-connect-6d87f',
    authDomain: 'campus-connect-6d87f.firebaseapp.com',
    storageBucket: 'campus-connect-6d87f.firebasestorage.app',
    measurementId: 'G-KNSH3DC1XB',
  );
}
